#!/bin/sh -l
set -o errexit
set -o xtrace

# Initialize the user's Monax environment.

go get -d github.com/monax/cli/cmd/monax
cd $GOPATH/src/github.com/monax/cli/cmd/monax
git checkout $BRANCH
go install
monax init --yes
